import { ImageType } from "@prisma/client";

export const upcomingAndPastEvents = {
  upcoming: [
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() + 1)),
      guests: [
        "luka@lunique.tech",
        "nikola@lunique.tech",
        "uros@lunique.tech",
        "vacic@lunique.tech",
        "zeljko@lunique.tech",
        "joka@lunique.tech",
        "teodora@lunique.tech",
        "marija@lunique.tech",
        "maja@lunique.tech",
        "test@test.com",
        "gmail@gmail.com",
      ],
      id: "1",
      images: [
        {
          id: "1",
          key: "image1",
          name: "Image 1",
          url: "https://example.com/image1.jpg",
          type: ImageType.JPG,
          eventId: "event1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "Belgrade, Serbia",
      name: "Hackathon",
      owner: {
        email: "john.doe@example.com",
        emailVerified: new Date(),
        id: "user1",
        image: "https://example.com/profile1.jpg",
        limit: 10,
        name: "John Doe",
      },
      ownerId: "user1",
      updatedAt: new Date(),
    },
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() + 5)),
      guests: [
        "luka@lunique.tech",
        "nikola@lunique.tech",
        "uros@lunique.tech",
        "vacic@lunique.tech",
        "maja@lunique.tech",
        "test@test.com",
        "gmail@gmail.com",
      ],
      id: "2",
      images: [
        {
          id: "2",
          key: "image2",
          name: "Image 2",
          url: "https://example.com/image2.jpg",
          type: ImageType.JPG,
          eventId: "event2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "Cuba",
      name: "Masterclass",
      owner: {
        email: "jane.smith@example.com",
        emailVerified: new Date(),
        id: "user2",
        image: "https://example.com/profile2.jpg",
        limit: 15,
        name: "Jane Smith",
      },
      ownerId: "user2",
      updatedAt: new Date(),
    },
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() + 3)),
      guests: [
        "luka@lunique.tech",
        "nikola@lunique.tech",
        "vacic@lunique.tech",
        "joka@lunique.tech",
        "marija@lunique.tech",
        "maja@lunique.tech",
        "test@test.com",
        "gmail@gmail.com",
      ],
      id: "3",
      images: [
        {
          id: "2",
          key: "image2",
          name: "Image 2",
          url: "https://example.com/image2.jpg",
          type: ImageType.JPG,
          eventId: "event2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "New York",
      name: "Math class",
      owner: {
        email: "jane.smith@example.com",
        emailVerified: new Date(),
        id: "user2",
        image: "https://example.com/profile2.jpg",
        limit: 15,
        name: "Jane Smith",
      },
      ownerId: "user2",
      updatedAt: new Date(),
    },
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() + 35)),
      guests: [
        "nikola@lunique.tech",
        "vacic@lunique.tech",
        "luka@lunique.tech",
        "vacic2@lte.com",
        "marija@lunique.tech",
        "test@test.com",
        "maja@lunique.tech",
        "joka@lunique.tech",
        "gmail@gmail.com",
      ],
      id: "4",
      images: [
        {
          id: "2",
          key: "image2",
          name: "Image 2",
          url: "https://example.com/image2.jpg",
          type: ImageType.JPG,
          eventId: "event2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "London",
      name: "Brainstorming",
      owner: {
        email: "jane.smith@example.com",
        emailVerified: new Date(),
        id: "user2",
        image: "https://example.com/profile2.jpg",
        limit: 15,
        name: "Jane Smith",
      },
      ownerId: "user2",
      updatedAt: new Date(),
    },
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() + 10)),
      guests: [
        "vacic@lunique.tech",
        "nikola@lunique.tech",
        "joka@lunique.tech",
        "gmail@gmail.com",
        "maja@lunique.tech",
        "marija@lunique.tech",
        "test@test.com",
        "luka@lunique.tech",
      ],
      id: "5",
      images: [
        {
          id: "2",
          key: "image2",
          name: "Image 2",
          url: "https://example.com/image2.jpg",
          type: ImageType.JPG,
          eventId: "event2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "Helsinki",
      name: "Call meeting",
      owner: {
        email: "jane.smith@example.com",
        emailVerified: new Date(),
        id: "user2",
        image: "https://example.com/profile2.jpg",
        limit: 15,
        name: "Jane Smith",
      },
      ownerId: "user2",
      updatedAt: new Date(),
    },
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() + 2)),
      guests: ["vacic@lunique.tech", "test@test.com", "gmail@gmail.com"],
      id: "6",
      images: [
        {
          id: "2",
          key: "image2",
          name: "Image 2",
          url: "https://example.com/image2.jpg",
          type: ImageType.JPG,
          eventId: "event2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "Barcelona",
      name: "Barcelona trip",
      owner: {
        email: "jane.smith@example.com",
        emailVerified: new Date(),
        id: "user2",
        image: "https://example.com/profile2.jpg",
        limit: 15,
        name: "Jane Smith",
      },
      ownerId: "user2",
      updatedAt: new Date(),
    },
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() + 7)),
      guests: [
        "vacic@lunique.tech",
        "luka@lunique.tech",
        "vacic2@lte.com",
        "marija@lunique.tech",
        "test@test.com",
        "maja@lunique.tech",
      ],
      id: "7",
      images: [
        {
          id: "2",
          key: "image2",
          name: "Image 2",
          url: "https://example.com/image2.jpg",
          type: ImageType.JPG,
          eventId: "event2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "Pague",
      name: "Business Conference",
      owner: {
        email: "jane.smith@example.com",
        emailVerified: new Date(),
        id: "user2",
        image: "https://example.com/profile2.jpg",
        limit: 15,
        name: "Jane Smith",
      },
      ownerId: "user2",
      updatedAt: new Date(),
    },
  ],
  past: [
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() - 5)),
      guests: ["nikola@lunique.tech"],
      id: "8",
      images: [
        {
          id: "2",
          key: "image2",
          name: "Image 2",
          url: "https://example.com/image2.jpg",
          type: ImageType.JPG,
          eventId: "event2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "Vancouver, Canada",
      name: "Masterclass",
      owner: {
        email: "jane.smith@example.com",
        emailVerified: new Date(),
        id: "user2",
        image: "https://example.com/profile2.jpg",
        limit: 15,
        name: "Jane Smith",
      },
      ownerId: "user2",
      updatedAt: new Date(),
    },
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() - 1)),
      guests: [],
      id: "9",
      images: [
        {
          id: "1",
          key: "image1",
          name: "Image 1",
          url: "https://example.com/image1.jpg",
          type: ImageType.JPG,
          eventId: "event1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "Belgrade, Serbia",
      name: "Group Basketball Trening",
      owner: {
        email: "john.doe@example.com",
        emailVerified: new Date(),
        id: "user1",
        image: "https://example.com/profile1.jpg",
        limit: 10,
        name: "John Doe",
      },
      ownerId: "user1",
      updatedAt: new Date(),
    },
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() - 3)),
      guests: [],
      id: "10",
      images: [
        {
          id: "2",
          key: "image2",
          name: "Image 2",
          url: "https://example.com/image2.jpg",
          type: ImageType.JPG,
          eventId: "event2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "Washington, US",
      name: "Math class",
      owner: {
        email: "jane.smith@example.com",
        emailVerified: new Date(),
        id: "user2",
        image: "https://example.com/profile2.jpg",
        limit: 15,
        name: "Jane Smith",
      },
      ownerId: "user2",
      updatedAt: new Date(),
    },
  ],
};

export const testimonials = [
  {
    name: "John Smith",
    email: "john.smith@example.com",
    impression:
      "Fantastic app! It has made organizing business events so much easier. The interface is very user-friendly, and the features are exactly what we needed. Highly recommend it!",
    image: "/images/invited/invited-1.webp",
  },
  {
    name: "Emma Johnson",
    email: "emma.johnson@example.com",
    impression:
      "Very intuitive and easy to use. It simplified the entire process of event planning. The customer support is excellent, and I always get quick responses. This app is a game-changer!",
    image: "/images/invited/invited-1.webp",
  },
  {
    name: "Michael Brown",
    email: "michael.brown@example.com",
    impression:
      "Everything I needed for successful event organization was found in this app. It has all the tools to manage events efficiently. The design is sleek and modern. I couldn't ask for more.",
    image: "/images/invited/invited-1.webp",
  },
  {
    name: "Emily Davis",
    email: "emily.davis@example.com",
    impression:
      "Exceptional support and user experience. The app saved my wedding planning! It covered every detail, making the whole process stress-free. I'm beyond satisfied.",
    image: "/images/invited/invited-1.webp",
  },
  {
    name: "William Wilson",
    email: "william.wilson@example.com",
    impression:
      "Outstanding application! It helped me keep everything organized and on track. The event went off without a hitch thanks to this app. I highly recommend it to anyone organizing an event.",
    image: "/images/invited/invited-1.webp",
  },
  {
    name: "Olivia Martinez",
    email: "olivia.martinez@example.com",
    impression:
      "This app is a lifesaver for event planning. It offers so many features that are incredibly useful. The calendar integration is seamless. It made my event planning experience wonderful.",
    image: "/images/invited/invited-1.webp",
  },
  {
    name: "James Anderson",
    email: "james.anderson@example.com",
    impression:
      "The best app for event management I've ever used. It keeps all my events in order and ensures nothing is forgotten. The reminders and notifications are very helpful. I love it!",
    image: "/images/invited/invited-1.webp",
  },
  {
    name: "Sophia Thomas",
    email: "sophia.thomas@example.com",
    impression:
      "A brilliant tool for organizing events. It made everything run so smoothly. I particularly appreciate the ability to customize details. Definitely a must-have for planners.",
    image: "/images/invited/invited-1.webp",
  },
  {
    name: "Benjamin Jackson",
    email: "benjamin.jackson@example.com",
    impression:
      "I can't believe how much this app has improved my event planning process. It’s packed with useful features and is very reliable. I’m very impressed with the level of detail. It's a fantastic app!",
    image: "/images/invited/invited-1.webp",
  },
  {
    name: "Mia White",
    email: "mia.white@example.com",
    impression:
      "An amazing app for anyone who needs to organize events. It made the entire process so much simpler and more efficient. The user interface is clean and easy to navigate. I highly recommend it!",
    image: "/images/invited/invited-1.webp",
  },
  {
    name: "Daniel Miller",
    email: "daniel.miller@example.com",
    impression:
      "This app revolutionized our event planning process. It’s incredibly efficient and easy to use. The customer service is top-notch. I highly recommend it to all event planners.",
    image: "/images/invited/invited-1.webp",
  },
  {
    name: "Sophia Taylor",
    email: "sophia.taylor@example.com",
    impression:
      "An excellent app for organizing events of all sizes. The features are comprehensive and very user-friendly. It made our event planning seamless. I couldn't be happier with the results.",
    image: "/images/invited/invited-2.webp",
  },
  {
    name: "David Lee",
    email: "david.lee@example.com",
    impression:
      "A must-have app for anyone involved in event management. It has simplified our processes tremendously. The intuitive design is fantastic. We’ve seen great improvements in efficiency.",
    image: "/images/invited/invited-3.webp",
  },
  {
    name: "Chloe Harris",
    email: "chloe.harris@example.com",
    impression:
      "Planning events has never been easier thanks to this app. The interface is very user-friendly and the features are incredibly useful. It saved us a lot of time and effort. Highly recommended!",
    image: "/images/invited/invited-4.webp",
  },
  {
    name: "Matthew Walker",
    email: "matthew.walker@example.com",
    impression:
      "This app is a real game-changer for event organizers. It's easy to use and has all the features we need. The support team is also very responsive. We are very pleased with our experience.",
    image: "/images/invited/invited-5.webp",
  },
  {
    name: "Amelia Hall",
    email: "amelia.hall@example.com",
    impression:
      "An incredible tool for event planning. It offers a wide range of features that cater to all our needs. The user interface is clean and straightforward. It made our event planning a breeze.",
    image: "/images/invited/invited-6.webp",
  },
  {
    name: "Christopher Young",
    email: "christopher.young@example.com",
    impression:
      "I love how easy and efficient this app makes event planning. It covers every aspect we need and more. The customer service is excellent. I would definitely recommend it to anyone planning an event.",
    image: "/images/invited/invited-7.webp",
  },
  {
    name: "Mia King",
    email: "mia.king@example.com",
    impression:
      "This app has made organizing events so much simpler. The features are comprehensive and very useful. It's incredibly user-friendly. We’ve had a great experience using it.",
    image: "/images/invited/invited-8.webp",
  },
  {
    name: "Jack Wright",
    email: "jack.wright@example.com",
    impression:
      "An amazing app for event management. It's easy to navigate and has everything we need. The support team is very helpful. It has greatly improved our event planning process.",
    image: "/images/invited/invited-9.webp",
  },
  {
    name: "Lily Scott",
    email: "lily.scott@example.com",
    impression:
      "A fantastic tool for anyone who needs to plan events. It’s packed with useful features and is very reliable. The user interface is intuitive. It has made our event planning much easier.",
    image: "/images/invited/invited-10.webp",
  },
];
