import { ImageType } from "@prisma/client";

export const upcomingAndPastEvents = {
  upcoming: [
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() + 1)),
      guests: [
        "luka@lunique.tech",
        "nikola@lunique.tech",
        "uros@lunique.tech",
        "vacic@lunique.tech",
        "zeljko@lunique.tech",
        "joka@lunique.tech",
        "teodora@lunique.tech",
        "marija@lunique.tech",
        "maja@lunique.tech",
        "test@test.com",
        "gmail@gmail.com",
      ],
      id: "1",
      images: [
        {
          id: "1",
          key: "image1",
          name: "Image 1",
          url: "https://example.com/image1.jpg",
          type: ImageType.JPG,
          eventId: "event1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "Belgrade, Serbia",
      name: "Hackathon",
      owner: {
        email: "john.doe@example.com",
        emailVerified: new Date(),
        id: "user1",
        image: "https://example.com/profile1.jpg",
        limit: 10,
        name: "John Doe",
      },
      ownerId: "user1",
      updatedAt: new Date(),
    },
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() + 5)),
      guests: [
        "luka@lunique.tech",
        "nikola@lunique.tech",
        "uros@lunique.tech",
        "vacic@lunique.tech",
        "maja@lunique.tech",
        "test@test.com",
        "gmail@gmail.com",
      ],
      id: "2",
      images: [
        {
          id: "2",
          key: "image2",
          name: "Image 2",
          url: "https://example.com/image2.jpg",
          type: ImageType.JPG,
          eventId: "event2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "Cuba",
      name: "Masterclass",
      owner: {
        email: "jane.smith@example.com",
        emailVerified: new Date(),
        id: "user2",
        image: "https://example.com/profile2.jpg",
        limit: 15,
        name: "Jane Smith",
      },
      ownerId: "user2",
      updatedAt: new Date(),
    },
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() + 3)),
      guests: [
        "luka@lunique.tech",
        "nikola@lunique.tech",
        "vacic@lunique.tech",
        "joka@lunique.tech",
        "marija@lunique.tech",
        "maja@lunique.tech",
        "test@test.com",
        "gmail@gmail.com",
      ],
      id: "3",
      images: [
        {
          id: "2",
          key: "image2",
          name: "Image 2",
          url: "https://example.com/image2.jpg",
          type: ImageType.JPG,
          eventId: "event2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "New York",
      name: "Math class",
      owner: {
        email: "jane.smith@example.com",
        emailVerified: new Date(),
        id: "user2",
        image: "https://example.com/profile2.jpg",
        limit: 15,
        name: "Jane Smith",
      },
      ownerId: "user2",
      updatedAt: new Date(),
    },
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() + 35)),
      guests: [
        "nikola@lunique.tech",
        "vacic@lunique.tech",
        "luka@lunique.tech",
        "vacic2@lte.com",
        "marija@lunique.tech",
        "test@test.com",
        "maja@lunique.tech",
        "joka@lunique.tech",
        "gmail@gmail.com",
      ],
      id: "4",
      images: [
        {
          id: "2",
          key: "image2",
          name: "Image 2",
          url: "https://example.com/image2.jpg",
          type: ImageType.JPG,
          eventId: "event2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "London",
      name: "Brainstorming",
      owner: {
        email: "jane.smith@example.com",
        emailVerified: new Date(),
        id: "user2",
        image: "https://example.com/profile2.jpg",
        limit: 15,
        name: "Jane Smith",
      },
      ownerId: "user2",
      updatedAt: new Date(),
    },
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() + 10)),
      guests: [
        "vacic@lunique.tech",
        "nikola@lunique.tech",
        "joka@lunique.tech",
        "gmail@gmail.com",
        "maja@lunique.tech",
        "marija@lunique.tech",
        "test@test.com",
        "luka@lunique.tech",
      ],
      id: "5",
      images: [
        {
          id: "2",
          key: "image2",
          name: "Image 2",
          url: "https://example.com/image2.jpg",
          type: ImageType.JPG,
          eventId: "event2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "Helsinki",
      name: "Call meeting",
      owner: {
        email: "jane.smith@example.com",
        emailVerified: new Date(),
        id: "user2",
        image: "https://example.com/profile2.jpg",
        limit: 15,
        name: "Jane Smith",
      },
      ownerId: "user2",
      updatedAt: new Date(),
    },
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() + 2)),
      guests: ["vacic@lunique.tech", "test@test.com", "gmail@gmail.com"],
      id: "6",
      images: [
        {
          id: "2",
          key: "image2",
          name: "Image 2",
          url: "https://example.com/image2.jpg",
          type: ImageType.JPG,
          eventId: "event2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "Barcelona",
      name: "Barcelona trip",
      owner: {
        email: "jane.smith@example.com",
        emailVerified: new Date(),
        id: "user2",
        image: "https://example.com/profile2.jpg",
        limit: 15,
        name: "Jane Smith",
      },
      ownerId: "user2",
      updatedAt: new Date(),
    },
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() + 7)),
      guests: [
        "vacic@lunique.tech",
        "luka@lunique.tech",
        "vacic2@lte.com",
        "marija@lunique.tech",
        "test@test.com",
        "maja@lunique.tech",
      ],
      id: "7",
      images: [
        {
          id: "2",
          key: "image2",
          name: "Image 2",
          url: "https://example.com/image2.jpg",
          type: ImageType.JPG,
          eventId: "event2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "Pague",
      name: "Business Conference",
      owner: {
        email: "jane.smith@example.com",
        emailVerified: new Date(),
        id: "user2",
        image: "https://example.com/profile2.jpg",
        limit: 15,
        name: "Jane Smith",
      },
      ownerId: "user2",
      updatedAt: new Date(),
    },
  ],
  past: [
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() - 5)),
      guests: ["nikola@lunique.tech"],
      id: "8",
      images: [
        {
          id: "2",
          key: "image2",
          name: "Image 2",
          url: "https://example.com/image2.jpg",
          type: ImageType.JPG,
          eventId: "event2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "Vancouver, Canada",
      name: "Masterclass",
      owner: {
        email: "jane.smith@example.com",
        emailVerified: new Date(),
        id: "user2",
        image: "https://example.com/profile2.jpg",
        limit: 15,
        name: "Jane Smith",
      },
      ownerId: "user2",
      updatedAt: new Date(),
    },
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() - 1)),
      guests: [],
      id: "9",
      images: [
        {
          id: "1",
          key: "image1",
          name: "Image 1",
          url: "https://example.com/image1.jpg",
          type: ImageType.JPG,
          eventId: "event1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "Belgrade, Serbia",
      name: "Group Basketball Trening",
      owner: {
        email: "john.doe@example.com",
        emailVerified: new Date(),
        id: "user1",
        image: "https://example.com/profile1.jpg",
        limit: 10,
        name: "John Doe",
      },
      ownerId: "user1",
      updatedAt: new Date(),
    },
    {
      createdAt: new Date(),
      date: new Date(new Date().setDate(new Date().getDate() - 3)),
      guests: [],
      id: "10",
      images: [
        {
          id: "2",
          key: "image2",
          name: "Image 2",
          url: "https://example.com/image2.jpg",
          type: ImageType.JPG,
          eventId: "event2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      location: "Washington, US",
      name: "Math class",
      owner: {
        email: "jane.smith@example.com",
        emailVerified: new Date(),
        id: "user2",
        image: "https://example.com/profile2.jpg",
        limit: 15,
        name: "Jane Smith",
      },
      ownerId: "user2",
      updatedAt: new Date(),
    },
  ],
};
