"use client";

import { useState } from "react";
import { CaretSortIcon } from "@radix-ui/react-icons";

import { Button } from "@/components/ui/button";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/components/ui/command";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";

interface EventTimezoneProps {
  value: string;
  onChange: (value: string) => void;
  isDirty: boolean;
}

export const EventTimezoneInput = ({ value, onChange }: EventTimezoneProps) => {
  const [commandValue, setCommandValue] = useState("");
  const [open, setOpen] = useState(false);

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button variant="outline" className=" justify-between">
          <span className="flex items-center gap-3">
            <span className="text-sm">
              {Object.entries(timezones)
                .find(([timezone]) => timezone === value)?.[1]
                .offset.replace("+", "+ ")}
            </span>
            <span className="text-sm text-muted-foreground">
              {
                Object.entries(timezones).find(
                  ([timezone]) => timezone === value,
                )?.[1].standard
              }
            </span>
          </span>
          <CaretSortIcon className="ml-2 size-4 shrink-0 opacity-50" />
        </Button>
      </PopoverTrigger>
      <PopoverContent align="end" className="w-full p-0">
        <Command>
          <div className="relative">
            <CommandInput
              value={commandValue}
              onValueChange={setCommandValue}
              placeholder="Search timezone..."
              className="h-9"
            />
          </div>
          <CommandList>
            <CommandEmpty>No timezone found.</CommandEmpty>

            <CommandGroup>
              {Object.entries(timezones).map(([timezone, attributes]) => (
                <CommandItem
                  key={timezone}
                  value={timezone}
                  onSelect={(value) => {
                    onChange(value);
                    setOpen(false);
                  }}
                  keywords={[attributes.offset]}
                  className="flex items-center justify-between"
                >
                  <p className="truncate text-sm">
                    {timezone.replaceAll("/", " - ").replaceAll("_", " ")}
                  </p>
                  <p className="w-28 text-right text-xs text-muted-foreground md:text-sm">
                    {attributes.offset}
                  </p>
                </CommandItem>
              ))}
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  );
};

const timezones = {
  "Africa/Abidjan": { offset: "+00:00", standard: "GMT" },
  "Africa/Accra": { offset: "+00:00", standard: "GMT" },
  "Africa/Addis_Ababa": { offset: "+03:00", standard: "EAT" },
  "Africa/Algiers": { offset: "+01:00", standard: "CET" },
  "Africa/Asmara": { offset: "+03:00", standard: "EAT" },
  "Africa/Asmera": { offset: "+03:00", standard: "EAT" },
  "Africa/Bamako": { offset: "+00:00", standard: "GMT" },
  "Africa/Bangui": { offset: "+01:00", standard: "WAT" },
  "Africa/Banjul": { offset: "+00:00", standard: "GMT" },
  "Africa/Bissau": { offset: "+00:00", standard: "GMT" },
  "Africa/Blantyre": { offset: "+02:00", standard: "CAT" },
  "Africa/Brazzaville": { offset: "+01:00", standard: "WAT" },
  "Africa/Bujumbura": { offset: "+02:00", standard: "CAT" },
  "Africa/Cairo": { offset: "+02:00", standard: "EET" },
  "Africa/Casablanca": {
    offset: "+01:00",
    standard: "+00:00",
    daylight: "+01",
    daylightStandard: "+00",
  },
  "Africa/Ceuta": {
    offset: "+01:00",
    standard: "+02:00",
    daylight: "CET",
    daylightStandard: "CEST",
  },
  "Africa/Conakry": { offset: "+00:00", standard: "GMT" },
  "Africa/Dakar": { offset: "+00:00", standard: "GMT" },
  "Africa/Dar_es_Salaam": { offset: "+03:00", standard: "EAT" },
  "Africa/Djibouti": { offset: "+03:00", standard: "EAT" },
  "Africa/Douala": { offset: "+01:00", standard: "WAT" },
  "Africa/El_Aaiun": {
    offset: "+01:00",
    standard: "+00:00",
    daylight: "+01",
    daylightStandard: "+00",
  },
  "Africa/Freetown": { offset: "+00:00", standard: "GMT" },
  "Africa/Gaborone": { offset: "+02:00", standard: "CAT" },
  "Africa/Harare": { offset: "+02:00", standard: "CAT" },
  "Africa/Johannesburg": { offset: "+02:00", standard: "SAST" },
  "Africa/Juba": { offset: "+02:00", standard: "CAT" },
  "Africa/Kampala": { offset: "+03:00", standard: "EAT" },
  "Africa/Khartoum": { offset: "+02:00", standard: "CAT" },
  "Africa/Kigali": { offset: "+02:00", standard: "CAT" },
  "Africa/Kinshasa": { offset: "+01:00", standard: "WAT" },
  "Africa/Lagos": { offset: "+01:00", standard: "WAT" },
  "Africa/Libreville": { offset: "+01:00", standard: "WAT" },
  "Africa/Lome": { offset: "+00:00", standard: "GMT" },
  "Africa/Luanda": { offset: "+01:00", standard: "WAT" },
  "Africa/Lubumbashi": { offset: "+02:00", standard: "CAT" },
  "Africa/Lusaka": { offset: "+02:00", standard: "CAT" },
  "Africa/Malabo": { offset: "+01:00", standard: "WAT" },
  "Africa/Maputo": { offset: "+02:00", standard: "CAT" },
  "Africa/Maseru": { offset: "+02:00", standard: "SAST" },
  "Africa/Mbabane": { offset: "+02:00", standard: "SAST" },
  "Africa/Mogadishu": { offset: "+03:00", standard: "EAT" },
  "Africa/Monrovia": { offset: "+00:00", standard: "GMT" },
  "Africa/Nairobi": { offset: "+03:00", standard: "EAT" },
  "Africa/Ndjamena": { offset: "+01:00", standard: "WAT" },
  "Africa/Niamey": { offset: "+01:00", standard: "WAT" },
  "Africa/Nouakchott": { offset: "+00:00", standard: "GMT" },
  "Africa/Ouagadougou": { offset: "+00:00", standard: "GMT" },
  "Africa/Porto-Novo": { offset: "+01:00", standard: "WAT" },
  "Africa/Sao_Tome": { offset: "+00:00", standard: "GMT" },
  "Africa/Timbuktu": { offset: "+00:00", standard: "GMT" },
  "Africa/Tripoli": { offset: "+02:00", standard: "EET" },
  "Africa/Tunis": { offset: "+01:00", standard: "CET" },
  "Africa/Windhoek": { offset: "+02:00", standard: "WAT" },
  "America/Adak": { offset: "-10:00", standard: "HST" },
  "America/Anchorage": { offset: "-09:00", standard: "AKST" },
  "America/Anguilla": { offset: "-04:00", standard: "AST" },
  "America/Antigua": { offset: "-04:00", standard: "AST" },
  "America/Araguaina": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Argentina/Buenos_Aires": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Argentina/Catamarca": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Argentina/ComodRivadavia": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Argentina/Cordoba": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Argentina/Jujuy": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Argentina/La_Rioja": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Argentina/Mendoza": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Argentina/Rio_Gallegos": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Argentina/Salta": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Argentina/San_Juan": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Argentina/San_Luis": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Argentina/Tucuman": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Argentina/Ushuaia": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Aruba": { offset: "-04:00", standard: "AST" },
  "America/Asuncion": {
    offset: "-04:00",
    standard: "-04:00",
    daylight: "-03",
    daylightStandard: "-04",
  },
  "America/Atikokan": { offset: "-05:00", standard: "EST" },
  "America/Atka": { offset: "-10:00", standard: "HST" },
  "America/Bahia": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Bahia_Banderas": { offset: "-06:00", standard: "CST" },
  "America/Barbados": { offset: "-04:00", standard: "AST" },
  "America/Belem": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Belize": { offset: "-06:00", standard: "CST" },
  "America/Blanc-Sablon": { offset: "-04:00", standard: "AST" },
  "America/Boa_Vista": {
    offset: "-04:00",
    standard: "-04:00",
    daylight: "-03",
    daylightStandard: "-04",
  },
  "America/Bogota": { offset: "-05:00", standard: "COT" },
  "America/Boise": { offset: "-07:00", standard: "MST" },
  "America/Buenos_Aires": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Cambridge_Bay": { offset: "-07:00", standard: "MST" },
  "America/Campo_Grande": {
    offset: "-04:00",
    standard: "-04:00",
    daylight: "-03",
    daylightStandard: "-04",
  },
  "America/Cancun": { offset: "-05:00", standard: "EST" },
  "America/Caracas": {
    offset: "-04:00",
    standard: "-04:00",
    daylight: "-04",
    daylightStandard: "-04",
  },
  "America/Catamarca": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Cayenne": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-03",
    daylightStandard: "-03",
  },
  "America/Cayman": { offset: "-05:00", standard: "EST" },
  "America/Chicago": { offset: "-06:00", standard: "CST" },
  "America/Chihuahua": { offset: "-07:00", standard: "MST" },
  "America/Coral_Harbour": { offset: "-05:00", standard: "EST" },
  "America/Cordoba": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Costa_Rica": { offset: "-06:00", standard: "CST" },
  "America/Creston": { offset: "-07:00", standard: "MST" },
  "America/Cuiaba": {
    offset: "-04:00",
    standard: "-04:00",
    daylight: "-03",
    daylightStandard: "-04",
  },
  "America/Curacao": { offset: "-04:00", standard: "AST" },
  "America/Danmarkshavn": { offset: "+00:00", standard: "GMT" },
  "America/Dawson": { offset: "-08:00", standard: "PST" },
  "America/Dawson_Creek": { offset: "-07:00", standard: "MST" },
  "America/Denver": { offset: "-06:00", standard: "MST" },
  "America/Detroit": { offset: "-04:00", standard: "EST" },
  "America/Dominica": { offset: "-04:00", standard: "AST" },
  "America/Edmonton": { offset: "-06:00", standard: "MST" },
  "America/Eirunepe": {
    offset: "-05:00",
    standard: "-05:00",
    daylight: "-05",
    daylightStandard: "-05",
  },
  "America/El_Salvador": { offset: "-06:00", standard: "CST" },
  "America/Ensenada": { offset: "-08:00", standard: "PST" },
  "America/Fort_Nelson": { offset: "-07:00", standard: "MST" },
  "America/Fort_Wayne": { offset: "-04:00", standard: "EST" },
  "America/Fortaleza": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Glace_Bay": { offset: "-03:00", standard: "AST" },
  "America/Godthab": {
    offset: "-02:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Goose_Bay": { offset: "-03:00", standard: "AST" },
  "America/Grand_Turk": { offset: "-04:00", standard: "AST" },
  "America/Grenada": { offset: "-04:00", standard: "AST" },
  "America/Guadeloupe": { offset: "-04:00", standard: "AST" },
  "America/Guatemala": { offset: "-06:00", standard: "CST" },
  "America/Guayaquil": { offset: "-05:00", standard: "ECT" },
  "America/Guyana": {
    offset: "-04:00",
    standard: "-04:00",
    daylight: "-03",
    daylightStandard: "-04",
  },
  "America/Halifax": { offset: "-03:00", standard: "AST" },
  "America/Havana": { offset: "-05:00", standard: "CST" },
  "America/Hermosillo": { offset: "-07:00", standard: "MST" },
  "America/Indiana/Indianapolis": { offset: "-04:00", standard: "EST" },
  "America/Indiana/Knox": { offset: "-05:00", standard: "EST" },
  "America/Indiana/Marengo": { offset: "-04:00", standard: "EST" },
  "America/Indiana/Petersburg": { offset: "-04:00", standard: "EST" },
  "America/Indiana/Tell_City": { offset: "-05:00", standard: "EST" },
  "America/Indiana/Vevay": { offset: "-04:00", standard: "EST" },
  "America/Indiana/Vincennes": { offset: "-04:00", standard: "EST" },
  "America/Indiana/Winamac": { offset: "-04:00", standard: "EST" },
  "America/Indianapolis": { offset: "-04:00", standard: "EST" },
  "America/Inuvik": { offset: "-06:00", standard: "MST" },
  "America/Iqaluit": { offset: "-04:00", standard: "EST" },
  "America/Jamaica": { offset: "-05:00", standard: "EST" },
  "America/Jujuy": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Juneau": { offset: "-08:00", standard: "AKST" },
  "America/Kentucky/Louisville": { offset: "-04:00", standard: "EST" },
  "America/Kentucky/Monticello": { offset: "-04:00", standard: "EST" },
  "America/Knox_IN": { offset: "-05:00", standard: "EST" },
  "America/Kralendijk": { offset: "-04:00", standard: "AST" },
  "America/La_Paz": {
    offset: "-04:00",
    standard: "-04:00",
    daylight: "-04",
    daylightStandard: "-04",
  },
  "America/Lima": {
    offset: "-05:00",
    standard: "-05:00",
    daylight: "-05",
    daylightStandard: "-05",
  },
  "America/Los_Angeles": { offset: "-08:00", standard: "PST" },
  "America/Louisville": { offset: "-04:00", standard: "EST" },
  "America/Lower_Princes": { offset: "-04:00", standard: "AST" },
  "America/Maceio": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Managua": { offset: "-06:00", standard: "CST" },
  "America/Manaus": {
    offset: "-04:00",
    standard: "-04:00",
    daylight: "-03",
    daylightStandard: "-04",
  },
  "America/Marigot": { offset: "-04:00", standard: "AST" },
  "America/Martinique": { offset: "-04:00", standard: "AST" },
  "America/Matamoros": { offset: "-06:00", standard: "CST" },
  "America/Mazatlan": { offset: "-07:00", standard: "MST" },
  "America/Mendoza": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Menominee": { offset: "-06:00", standard: "CST" },
  "America/Merida": { offset: "-06:00", standard: "CST" },
  "America/Metlakatla": { offset: "-08:00", standard: "PST" },
  "America/Mexico_City": { offset: "-06:00", standard: "CST" },
  "America/Miquelon": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Moncton": { offset: "-03:00", standard: "AST" },
  "America/Monterrey": { offset: "-06:00", standard: "CST" },
  "America/Montevideo": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Montreal": { offset: "-04:00", standard: "EST" },
  "America/Montserrat": { offset: "-04:00", standard: "AST" },
  "America/Nassau": { offset: "-04:00", standard: "EST" },
  "America/New_York": { offset: "-04:00", standard: "EST" },
  "America/Nipigon": { offset: "-04:00", standard: "EST" },
  "America/Nome": { offset: "-08:00", standard: "AKST" },
  "America/Noronha": {
    offset: "-02:00",
    standard: "-02:00",
    daylight: "-01",
    daylightStandard: "-02",
  },
  "America/North_Dakota/Beulah": { offset: "-06:00", standard: "CST" },
  "America/North_Dakota/Center": { offset: "-06:00", standard: "CST" },
  "America/North_Dakota/New_Salem": { offset: "-06:00", standard: "CST" },
  "America/Ojinaga": { offset: "-07:00", standard: "MST" },
  "America/Panama": { offset: "-05:00", standard: "EST" },
  "America/Pangnirtung": { offset: "-04:00", standard: "EST" },
  "America/Paramaribo": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-03",
    daylightStandard: "-03",
  },
  "America/Phoenix": { offset: "-07:00", standard: "MST" },
  "America/Port-au-Prince": { offset: "-05:00", standard: "EST" },
  "America/Port_of_Spain": { offset: "-04:00", standard: "AST" },
  "America/Porto_Acre": {
    offset: "-05:00",
    standard: "-05:00",
    daylight: "-05",
    daylightStandard: "-05",
  },
  "America/Porto_Velho": {
    offset: "-04:00",
    standard: "-04:00",
    daylight: "-03",
    daylightStandard: "-04",
  },
  "America/Puerto_Rico": { offset: "-04:00", standard: "AST" },
  "America/Punta_Arenas": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-03",
    daylightStandard: "-03",
  },
  "America/Rainy_River": { offset: "-05:00", standard: "EST" },
  "America/Rankin_Inlet": { offset: "-05:00", standard: "EST" },
  "America/Recife": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Regina": { offset: "-06:00", standard: "CST" },
  "America/Resolute": { offset: "-05:00", standard: "EST" },
  "America/Rio_Branco": {
    offset: "-05:00",
    standard: "-05:00",
    daylight: "-05",
    daylightStandard: "-05",
  },
  "America/Rosario": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Santa_Isabel": { offset: "-08:00", standard: "PST" },
  "America/Santarem": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Santiago": {
    offset: "-04:00",
    standard: "-04:00",
    daylight: "-03",
    daylightStandard: "-04",
  },
  "America/Santo_Domingo": { offset: "-04:00", standard: "AST" },
  "America/Sao_Paulo": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "America/Scoresbysund": {
    offset: "-01:00",
    standard: "-02:00",
    daylight: "+00",
    daylightStandard: "-01",
  },
  "America/Shiprock": { offset: "-06:00", standard: "MST" },
  "America/Sitka": { offset: "-08:00", standard: "AKST" },
  "America/St_Barthelemy": { offset: "-04:00", standard: "AST" },
  "America/St_Johns": { offset: "-02:30", standard: "NST" },
  "America/St_Kitts": { offset: "-04:00", standard: "AST" },
  "America/St_Lucia": { offset: "-04:00", standard: "AST" },
  "America/St_Thomas": { offset: "-04:00", standard: "AST" },
  "America/St_Vincent": { offset: "-04:00", standard: "AST" },
  "America/Swift_Current": { offset: "-06:00", standard: "CST" },
  "America/Tegucigalpa": { offset: "-06:00", standard: "CST" },
  "America/Thule": { offset: "-04:00", standard: "AST" },
  "America/Thunder_Bay": { offset: "-04:00", standard: "EST" },
  "America/Tijuana": { offset: "-08:00", standard: "PST" },
  "America/Toronto": { offset: "-04:00", standard: "EST" },
  "America/Tortola": { offset: "-04:00", standard: "AST" },
  "America/Vancouver": { offset: "-08:00", standard: "PST" },
  "America/Virgin": { offset: "-04:00", standard: "AST" },
  "America/Whitehorse": { offset: "-08:00", standard: "PST" },
  "America/Winnipeg": { offset: "-06:00", standard: "CST" },
  "America/Yakutat": { offset: "-09:00", standard: "AKST" },
  "America/Yellowknife": { offset: "-06:00", standard: "MST" },
  "Antarctica/Casey": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+11",
    daylightStandard: "+08",
  },
  "Antarctica/Davis": {
    offset: "+07:00",
    standard: "+07:00",
    daylight: "+07",
    daylightStandard: "+07",
  },
  "Antarctica/DumontDUrville": {
    offset: "+10:00",
    standard: "+10:00",
    daylight: "+10",
    daylightStandard: "+10",
  },
  "Antarctica/Macquarie": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Antarctica/Mawson": {
    offset: "+05:00",
    standard: "+05:00",
    daylight: "+05",
    daylightStandard: "+05",
  },
  "Antarctica/McMurdo": {
    offset: "+12:00",
    standard: "+12:00",
    daylight: "+13",
    daylightStandard: "+12",
  },
  "Antarctica/Palmer": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-03",
    daylightStandard: "-03",
  },
  "Antarctica/Rothera": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-03",
    daylightStandard: "-03",
  },
  "Antarctica/South_Pole": {
    offset: "+12:00",
    standard: "+12:00",
    daylight: "+13",
    daylightStandard: "+12",
  },
  "Antarctica/Syowa": {
    offset: "+03:00",
    standard: "+03:00",
    daylight: "+03",
    daylightStandard: "+03",
  },
  "Antarctica/Troll": { offset: "+00:00", standard: "WAT" },
  "Antarctica/Vostok": {
    offset: "+06:00",
    standard: "+06:00",
    daylight: "+06",
    daylightStandard: "+06",
  },
  "Arctic/Longyearbyen": { offset: "+01:00", standard: "CET" },
  "Asia/Aden": {
    offset: "+03:00",
    standard: "+03:00",
    daylight: "+03",
    daylightStandard: "+03",
  },
  "Asia/Almaty": {
    offset: "+06:00",
    standard: "+06:00",
    daylight: "+06",
    daylightStandard: "+06",
  },
  "Asia/Amman": { offset: "+03:00", standard: "EET" },
  "Asia/Anadyr": {
    offset: "+12:00",
    standard: "+12:00",
    daylight: "+12",
    daylightStandard: "+12",
  },
  "Asia/Aqtau": {
    offset: "+05:00",
    standard: "+05:00",
    daylight: "+05",
    daylightStandard: "+05",
  },
  "Asia/Aqtobe": {
    offset: "+05:00",
    standard: "+05:00",
    daylight: "+05",
    daylightStandard: "+05",
  },
  "Asia/Ashgabat": {
    offset: "+05:00",
    standard: "+05:00",
    daylight: "+05",
    daylightStandard: "+05",
  },
  "Asia/Ashkhabad": {
    offset: "+05:00",
    standard: "+05:00",
    daylight: "+05",
    daylightStandard: "+05",
  },
  "Asia/Atyrau": {
    offset: "+05:00",
    standard: "+05:00",
    daylight: "+05",
    daylightStandard: "+05",
  },
  "Asia/Baghdad": {
    offset: "+03:00",
    standard: "+03:00",
    daylight: "+03",
    daylightStandard: "+03",
  },
  "Asia/Bahrain": {
    offset: "+03:00",
    standard: "+03:00",
    daylight: "+03",
    daylightStandard: "+03",
  },
  "Asia/Baku": {
    offset: "+04:00",
    standard: "+04:00",
    daylight: "+04",
    daylightStandard: "+04",
  },
  "Asia/Bangkok": {
    offset: "+07:00",
    standard: "+07:00",
    daylight: "+07",
    daylightStandard: "+07",
  },
  "Asia/Barnaul": {
    offset: "+07:00",
    standard: "+07:00",
    daylight: "+07",
    daylightStandard: "+07",
  },
  "Asia/Beirut": { offset: "+03:00", standard: "EET" },
  "Asia/Bishkek": {
    offset: "+06:00",
    standard: "+06:00",
    daylight: "+06",
    daylightStandard: "+06",
  },
  "Asia/Brunei": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Asia/Calcutta": {
    offset: "+05:30",
    standard: "+05:30",
    daylight: "+05:30",
    daylightStandard: "+05:30",
  },
  "Asia/Chita": {
    offset: "+09:00",
    standard: "+09:00",
    daylight: "+09",
    daylightStandard: "+09",
  },
  "Asia/Choibalsan": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Asia/Chongqing": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Asia/Chungking": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Asia/Colombo": {
    offset: "+05:30",
    standard: "+05:30",
    daylight: "+05:30",
    daylightStandard: "+05:30",
  },
  "Asia/Dacca": {
    offset: "+06:00",
    standard: "+06:00",
    daylight: "+06",
    daylightStandard: "+06",
  },
  "Asia/Damascus": { offset: "+03:00", standard: "EET" },
  "Asia/Dhaka": {
    offset: "+06:00",
    standard: "+06:00",
    daylight: "+06",
    daylightStandard: "+06",
  },
  "Asia/Dili": {
    offset: "+09:00",
    standard: "+09:00",
    daylight: "+09",
    daylightStandard: "+09",
  },
  "Asia/Dubai": {
    offset: "+04:00",
    standard: "+04:00",
    daylight: "+04",
    daylightStandard: "+04",
  },
  "Asia/Dushanbe": {
    offset: "+05:00",
    standard: "+05:00",
    daylight: "+05",
    daylightStandard: "+05",
  },
  "Asia/Famagusta": {
    offset: "+03:00",
    standard: "+03:00",
    daylight: "+03",
    daylightStandard: "+03",
  },
  "Asia/Gaza": { offset: "+03:00", standard: "EET" },
  "Asia/Harbin": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Asia/Hebron": { offset: "+03:00", standard: "EET" },
  "Asia/Ho_Chi_Minh": {
    offset: "+07:00",
    standard: "+07:00",
    daylight: "+07",
    daylightStandard: "+07",
  },
  "Asia/Hong_Kong": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Asia/Hovd": {
    offset: "+07:00",
    standard: "+07:00",
    daylight: "+07",
    daylightStandard: "+07",
  },
  "Asia/Irkutsk": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Asia/Istanbul": {
    offset: "+03:00",
    standard: "+03:00",
    daylight: "+03",
    daylightStandard: "+03",
  },
  "Asia/Jakarta": {
    offset: "+07:00",
    standard: "+07:00",
    daylight: "+07",
    daylightStandard: "+07",
  },
  "Asia/Jayapura": {
    offset: "+09:00",
    standard: "+09:00",
    daylight: "+09",
    daylightStandard: "+09",
  },
  "Asia/Jerusalem": { offset: "+03:00", standard: "IST" },
  "Asia/Kabul": {
    offset: "+04:30",
    standard: "+04:30",
    daylight: "+04:30",
    daylightStandard: "+04:30",
  },
  "Asia/Kamchatka": {
    offset: "+12:00",
    standard: "+12:00",
    daylight: "+12",
    daylightStandard: "+12",
  },
  "Asia/Karachi": {
    offset: "+05:00",
    standard: "+05:00",
    daylight: "+05",
    daylightStandard: "+05",
  },
  "Asia/Kashgar": {
    offset: "+06:00",
    standard: "+06:00",
    daylight: "+06",
    daylightStandard: "+06",
  },
  "Asia/Kathmandu": {
    offset: "+05:45",
    standard: "+05:45",
    daylight: "+05:45",
    daylightStandard: "+05:45",
  },
  "Asia/Katmandu": {
    offset: "+05:45",
    standard: "+05:45",
    daylight: "+05:45",
    daylightStandard: "+05:45",
  },
  "Asia/Khandyga": {
    offset: "+09:00",
    standard: "+09:00",
    daylight: "+09",
    daylightStandard: "+09",
  },
  "Asia/Kolkata": {
    offset: "+05:30",
    standard: "+05:30",
    daylight: "+05:30",
    daylightStandard: "+05:30",
  },
  "Asia/Krasnoyarsk": {
    offset: "+07:00",
    standard: "+07:00",
    daylight: "+07",
    daylightStandard: "+07",
  },
  "Asia/Kuala_Lumpur": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Asia/Kuching": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Asia/Kuwait": {
    offset: "+03:00",
    standard: "+03:00",
    daylight: "+03",
    daylightStandard: "+03",
  },
  "Asia/Macao": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Asia/Macau": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Asia/Magadan": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Asia/Makassar": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Asia/Manila": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Asia/Muscat": {
    offset: "+04:00",
    standard: "+04:00",
    daylight: "+04",
    daylightStandard: "+04",
  },
  "Asia/Nicosia": { offset: "+03:00", standard: "EET" },
  "Asia/Novokuznetsk": {
    offset: "+07:00",
    standard: "+07:00",
    daylight: "+07",
    daylightStandard: "+07",
  },
  "Asia/Novosibirsk": {
    offset: "+07:00",
    standard: "+07:00",
    daylight: "+07",
    daylightStandard: "+07",
  },
  "Asia/Omsk": {
    offset: "+06:00",
    standard: "+06:00",
    daylight: "+06",
    daylightStandard: "+06",
  },
  "Asia/Oral": {
    offset: "+05:00",
    standard: "+05:00",
    daylight: "+05",
    daylightStandard: "+05",
  },
  "Asia/Phnom_Penh": {
    offset: "+07:00",
    standard: "+07:00",
    daylight: "+07",
    daylightStandard: "+07",
  },
  "Asia/Pontianak": {
    offset: "+07:00",
    standard: "+07:00",
    daylight: "+07",
    daylightStandard: "+07",
  },
  "Asia/Pyongyang": {
    offset: "+09:00",
    standard: "+09:00",
    daylight: "+09",
    daylightStandard: "+09",
  },
  "Asia/Qatar": {
    offset: "+03:00",
    standard: "+03:00",
    daylight: "+03",
    daylightStandard: "+03",
  },
  "Asia/Qostanay": {
    offset: "+06:00",
    standard: "+06:00",
    daylight: "+06",
    daylightStandard: "+06",
  },
  "Asia/Qyzylorda": {
    offset: "+06:00",
    standard: "+06:00",
    daylight: "+06",
    daylightStandard: "+06",
  },
  "Asia/Rangoon": {
    offset: "+06:30",
    standard: "+06:30",
    daylight: "+06:30",
    daylightStandard: "+06:30",
  },
  "Asia/Riyadh": {
    offset: "+03:00",
    standard: "+03:00",
    daylight: "+03",
    daylightStandard: "+03",
  },
  "Asia/Saigon": {
    offset: "+07:00",
    standard: "+07:00",
    daylight: "+07",
    daylightStandard: "+07",
  },
  "Asia/Sakhalin": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Asia/Samarkand": {
    offset: "+05:00",
    standard: "+05:00",
    daylight: "+05",
    daylightStandard: "+05",
  },
  "Asia/Seoul": {
    offset: "+09:00",
    standard: "+09:00",
    daylight: "+09",
    daylightStandard: "+09",
  },
  "Asia/Shanghai": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Asia/Singapore": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Asia/Srednekolymsk": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Asia/Taipei": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Asia/Tashkent": {
    offset: "+05:00",
    standard: "+05:00",
    daylight: "+05",
    daylightStandard: "+05",
  },
  "Asia/Tbilisi": {
    offset: "+04:00",
    standard: "+04:00",
    daylight: "+04",
    daylightStandard: "+04",
  },
  "Asia/Tehran": {
    offset: "+04:30",
    standard: "+04:30",
    daylight: "+04:30",
    daylightStandard: "+04:30",
  },
  "Asia/Tel_Aviv": { offset: "+03:00", standard: "IST" },
  "Asia/Thimbu": {
    offset: "+06:00",
    standard: "+06:00",
    daylight: "+06",
    daylightStandard: "+06",
  },
  "Asia/Thimphu": {
    offset: "+06:00",
    standard: "+06:00",
    daylight: "+06",
    daylightStandard: "+06",
  },
  "Asia/Tokyo": {
    offset: "+09:00",
    standard: "+09:00",
    daylight: "+09",
    daylightStandard: "+09",
  },
  "Asia/Tomsk": {
    offset: "+07:00",
    standard: "+07:00",
    daylight: "+07",
    daylightStandard: "+07",
  },
  "Asia/Ujung_Pandang": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Asia/Ulaanbaatar": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Asia/Ulan_Bator": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Asia/Urumqi": {
    offset: "+06:00",
    standard: "+06:00",
    daylight: "+06",
    daylightStandard: "+06",
  },
  "Asia/Ust-Nera": {
    offset: "+10:00",
    standard: "+10:00",
    daylight: "+10",
    daylightStandard: "+10",
  },
  "Asia/Vientiane": {
    offset: "+07:00",
    standard: "+07:00",
    daylight: "+07",
    daylightStandard: "+07",
  },
  "Asia/Vladivostok": {
    offset: "+10:00",
    standard: "+10:00",
    daylight: "+10",
    daylightStandard: "+10",
  },
  "Asia/Yakutsk": {
    offset: "+09:00",
    standard: "+09:00",
    daylight: "+09",
    daylightStandard: "+09",
  },
  "Asia/Yangon": {
    offset: "+06:30",
    standard: "+06:30",
    daylight: "+06:30",
    daylightStandard: "+06:30",
  },
  "Asia/Yekaterinburg": {
    offset: "+05:00",
    standard: "+05:00",
    daylight: "+05",
    daylightStandard: "+05",
  },
  "Asia/Yerevan": {
    offset: "+04:00",
    standard: "+04:00",
    daylight: "+04",
    daylightStandard: "+04",
  },
  "Atlantic/Azores": {
    offset: "-01:00",
    standard: "-01:00",
    daylight: "+00",
    daylightStandard: "-01",
  },
  "Atlantic/Bermuda": { offset: "-03:00", standard: "AST" },
  "Atlantic/Canary": { offset: "+00:00", standard: "WET" },
  "Atlantic/Cape_Verde": {
    offset: "-01:00",
    standard: "-01:00",
    daylight: "-01",
    daylightStandard: "-01",
  },
  "Atlantic/Faeroe": { offset: "+00:00", standard: "WET" },
  "Atlantic/Faroe": { offset: "+00:00", standard: "WET" },
  "Atlantic/Jan_Mayen": { offset: "+01:00", standard: "CET" },
  "Atlantic/Madeira": { offset: "+00:00", standard: "WET" },
  "Atlantic/Reykjavik": { offset: "+00:00", standard: "WET" },
  "Atlantic/South_Georgia": {
    offset: "-02:00",
    standard: "-02:00",
    daylight: "+00",
    daylightStandard: "-02",
  },
  "Atlantic/St_Helena": { offset: "+00:00", standard: "WET" },
  "Atlantic/Stanley": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-03",
    daylightStandard: "-03",
  },
  "Australia/ACT": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Australia/Adelaide": {
    offset: "+10:30",
    standard: "+09:30",
    daylight: "+10",
    daylightStandard: "+09",
  },
  "Australia/Brisbane": {
    offset: "+10:00",
    standard: "+10:00",
    daylight: "+10",
    daylightStandard: "+10",
  },
  "Australia/Broken_Hill": {
    offset: "+10:30",
    standard: "+09:30",
    daylight: "+10",
    daylightStandard: "+09",
  },
  "Australia/Canberra": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Australia/Currie": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Australia/Darwin": {
    offset: "+09:30",
    standard: "+09:30",
    daylight: "+09",
    daylightStandard: "+09",
  },
  "Australia/Eucla": {
    offset: "+08:45",
    standard: "+08:45",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Australia/Hobart": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Australia/LHI": {
    offset: "+10:30",
    standard: "+10:30",
    daylight: "+11",
    daylightStandard: "+10",
  },
  "Australia/Lindeman": {
    offset: "+10:00",
    standard: "+10:00",
    daylight: "+10",
    daylightStandard: "+10",
  },
  "Australia/Lord_Howe": {
    offset: "+10:30",
    standard: "+10:30",
    daylight: "+11",
    daylightStandard: "+10",
  },
  "Australia/Melbourne": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Australia/NSW": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Australia/North": {
    offset: "+09:30",
    standard: "+09:30",
    daylight: "+09",
    daylightStandard: "+09",
  },
  "Australia/Perth": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Australia/Queensland": {
    offset: "+10:00",
    standard: "+10:00",
    daylight: "+10",
    daylightStandard: "+10",
  },
  "Australia/South": {
    offset: "+10:30",
    standard: "+09:30",
    daylight: "+10",
    daylightStandard: "+09",
  },
  "Australia/Sydney": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Australia/Tasmania": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Australia/Victoria": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Australia/West": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  "Australia/Yancowinna": {
    offset: "+10:30",
    standard: "+09:30",
    daylight: "+10",
    daylightStandard: "+09",
  },
  "Brazil/Acre": {
    offset: "-05:00",
    standard: "-05:00",
    daylight: "-05",
    daylightStandard: "-05",
  },
  "Brazil/DeNoronha": {
    offset: "-02:00",
    standard: "-02:00",
    daylight: "-02",
    daylightStandard: "-02",
  },
  "Brazil/East": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-03",
    daylightStandard: "-03",
  },
  "Brazil/West": {
    offset: "-04:00",
    standard: "-04:00",
    daylight: "-04",
    daylightStandard: "-04",
  },
  CET: { offset: "+01:00", standard: "CET" },
  CST6CDT: {
    offset: "-06:00",
    standard: "-06:00",
    daylight: "-05",
    daylightStandard: "-06",
  },
  "Canada/Atlantic": {
    offset: "-04:00",
    standard: "-04:00",
    daylight: "-03",
    daylightStandard: "-04",
  },
  "Canada/Central": {
    offset: "-06:00",
    standard: "-06:00",
    daylight: "-05",
    daylightStandard: "-06",
  },
  "Canada/Eastern": {
    offset: "-05:00",
    standard: "-05:00",
    daylight: "-04",
    daylightStandard: "-05",
  },
  "Canada/Mountain": {
    offset: "-07:00",
    standard: "-07:00",
    daylight: "-06",
    daylightStandard: "-07",
  },
  "Canada/Newfoundland": {
    offset: "-03:30",
    standard: "-03:30",
    daylight: "-02",
    daylightStandard: "-03",
  },
  "Canada/Pacific": {
    offset: "-08:00",
    standard: "-08:00",
    daylight: "-07",
    daylightStandard: "-08",
  },
  "Canada/Saskatchewan": {
    offset: "-06:00",
    standard: "-06:00",
    daylight: "-06",
    daylightStandard: "-06",
  },
  "Canada/Yukon": {
    offset: "-08:00",
    standard: "-08:00",
    daylight: "-07",
    daylightStandard: "-08",
  },
  "Chile/Continental": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "-04",
    daylightStandard: "-03",
  },
  "Chile/EasterIsland": {
    offset: "-05:00",
    standard: "-05:00",
    daylight: "-06",
    daylightStandard: "-05",
  },
  Cuba: {
    offset: "-05:00",
    standard: "-05:00",
    daylight: "-04",
    daylightStandard: "-05",
  },
  EET: { offset: "+02:00", standard: "EET" },
  EST: {
    offset: "-05:00",
    standard: "-05:00",
    daylight: "-05",
    daylightStandard: "-05",
  },
  EST5EDT: {
    offset: "-05:00",
    standard: "-05:00",
    daylight: "-04",
    daylightStandard: "-05",
  },
  Egypt: {
    offset: "+02:00",
    standard: "+02:00",
    daylight: "+03",
    daylightStandard: "+02",
  },
  Eire: { offset: "+00:00", standard: "WET" },
  "Etc/GMT": { offset: "+00:00", standard: "GMT" },
  "Etc/GMT+0": { offset: "+00:00", standard: "GMT" },
  "Etc/GMT+1": {
    offset: "-01:00",
    standard: "-01:00",
    daylight: "+00",
    daylightStandard: "-01",
  },
  "Etc/GMT+10": {
    offset: "-10:00",
    standard: "-10:00",
    daylight: "-10",
    daylightStandard: "-10",
  },
  "Etc/GMT+11": {
    offset: "-11:00",
    standard: "-11:00",
    daylight: "-11",
    daylightStandard: "-11",
  },
  "Etc/GMT+12": {
    offset: "-12:00",
    standard: "-12:00",
    daylight: "-12",
    daylightStandard: "-12",
  },
  "Etc/GMT+2": {
    offset: "-02:00",
    standard: "-02:00",
    daylight: "+00",
    daylightStandard: "-02",
  },
  "Etc/GMT+3": {
    offset: "-03:00",
    standard: "-03:00",
    daylight: "+00",
    daylightStandard: "-03",
  },
  "Etc/GMT+4": {
    offset: "-04:00",
    standard: "-04:00",
    daylight: "+00",
    daylightStandard: "-04",
  },
  "Etc/GMT+5": {
    offset: "-05:00",
    standard: "-05:00",
    daylight: "+00",
    daylightStandard: "-05",
  },
  "Etc/GMT+6": {
    offset: "-06:00",
    standard: "-06:00",
    daylight: "+00",
    daylightStandard: "-06",
  },
  "Etc/GMT+7": {
    offset: "-07:00",
    standard: "-07:00",
    daylight: "+00",
    daylightStandard: "-07",
  },
  "Etc/GMT+8": {
    offset: "-08:00",
    standard: "-08:00",
    daylight: "+00",
    daylightStandard: "-08",
  },
  "Etc/GMT+9": {
    offset: "-09:00",
    standard: "-09:00",
    daylight: "+00",
    daylightStandard: "-09",
  },
  "Etc/GMT-0": { offset: "+00:00", standard: "GMT" },
  "Etc/GMT-1": {
    offset: "+01:00",
    standard: "+01:00",
    daylight: "+00",
    daylightStandard: "+01",
  },
  "Etc/GMT-10": {
    offset: "+10:00",
    standard: "+10:00",
    daylight: "+10",
    daylightStandard: "+10",
  },
  "Etc/GMT-11": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Etc/GMT-12": {
    offset: "+12:00",
    standard: "+12:00",
    daylight: "+12",
    daylightStandard: "+12",
  },
  "Etc/GMT-13": {
    offset: "+13:00",
    standard: "+13:00",
    daylight: "+13",
    daylightStandard: "+13",
  },
  "Etc/GMT-14": {
    offset: "+14:00",
    standard: "+14:00",
    daylight: "+14",
    daylightStandard: "+14",
  },
  "Etc/GMT-2": {
    offset: "+02:00",
    standard: "+02:00",
    daylight: "+00",
    daylightStandard: "+02",
  },
  "Etc/GMT-3": {
    offset: "+03:00",
    standard: "+03:00",
    daylight: "+00",
    daylightStandard: "+03",
  },
  "Etc/GMT-4": {
    offset: "+04:00",
    standard: "+04:00",
    daylight: "+00",
    daylightStandard: "+04",
  },
  "Etc/GMT-5": {
    offset: "+05:00",
    standard: "+05:00",
    daylight: "+00",
    daylightStandard: "+05",
  },
  "Etc/GMT-6": {
    offset: "+06:00",
    standard: "+06:00",
    daylight: "+00",
    daylightStandard: "+06",
  },
  "Etc/GMT-7": {
    offset: "+07:00",
    standard: "+07:00",
    daylight: "+00",
    daylightStandard: "+07",
  },
  "Etc/GMT-8": {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+00",
    daylightStandard: "+08",
  },
  "Etc/GMT-9": {
    offset: "+09:00",
    standard: "+09:00",
    daylight: "+00",
    daylightStandard: "+09",
  },
  "Etc/GMT0": { offset: "+00:00", standard: "GMT" },
  "Etc/Greenwich": { offset: "+00:00", standard: "GMT" },
  "Etc/UCT": { offset: "+00:00", standard: "GMT" },
  "Etc/UTC": { offset: "+00:00", standard: "GMT" },
  "Etc/Universal": { offset: "+00:00", standard: "GMT" },
  "Etc/Zulu": { offset: "+00:00", standard: "GMT" },
  "Europe/Amsterdam": { offset: "+02:00", standard: "CEST" },
  "Europe/Andorra": { offset: "+02:00", standard: "CEST" },
  "Europe/Astrakhan": {
    offset: "+04:00",
    standard: "+04:00",
    daylight: "+04",
    daylightStandard: "+04",
  },
  "Europe/Athens": { offset: "+03:00", standard: "EEST" },
  "Europe/Belfast": { offset: "+01:00", standard: "BST" },
  "Europe/Belgrade": { offset: "+02:00", standard: "CEST" },
  "Europe/Berlin": { offset: "+02:00", standard: "CEST" },
  "Europe/Bratislava": { offset: "+02:00", standard: "CEST" },
  "Europe/Brussels": { offset: "+02:00", standard: "CEST" },
  "Europe/Bucharest": { offset: "+03:00", standard: "EEST" },
  "Europe/Budapest": { offset: "+02:00", standard: "CEST" },
  "Europe/Busingen": { offset: "+02:00", standard: "CEST" },
  "Europe/Chisinau": { offset: "+03:00", standard: "EEST" },
  "Europe/Copenhagen": { offset: "+02:00", standard: "CEST" },
  "Europe/Dublin": { offset: "+01:00", standard: "IST" },
  "Europe/Gibraltar": { offset: "+02:00", standard: "CEST" },
  "Europe/Guernsey": { offset: "+01:00", standard: "BST" },
  "Europe/Helsinki": { offset: "+03:00", standard: "EEST" },
  "Europe/Isle_of_Man": { offset: "+01:00", standard: "BST" },
  "Europe/Istanbul": { offset: "+03:00", standard: "TRT" },
  "Europe/Jersey": { offset: "+01:00", standard: "BST" },
  "Europe/Kaliningrad": {
    offset: "+02:00",
    standard: "+02:00",
    daylight: "+02",
    daylightStandard: "+02",
  },
  "Europe/Kiev": { offset: "+03:00", standard: "EEST" },
  "Europe/Kirov": {
    offset: "+03:00",
    standard: "+03:00",
    daylight: "+03",
    daylightStandard: "+03",
  },
  "Europe/Lisbon": { offset: "+01:00", standard: "WEST" },
  "Europe/Ljubljana": { offset: "+02:00", standard: "CEST" },
  "Europe/London": { offset: "+01:00", standard: "BST" },
  "Europe/Luxembourg": { offset: "+02:00", standard: "CEST" },
  "Europe/Madrid": { offset: "+02:00", standard: "CEST" },
  "Europe/Malta": { offset: "+02:00", standard: "CEST" },
  "Europe/Mariehamn": { offset: "+03:00", standard: "EEST" },
  "Europe/Minsk": {
    offset: "+03:00",
    standard: "+03:00",
    daylight: "+03",
    daylightStandard: "+03",
  },
  "Europe/Monaco": { offset: "+02:00", standard: "CEST" },
  "Europe/Moscow": {
    offset: "+03:00",
    standard: "+03:00",
    daylight: "+03",
    daylightStandard: "+03",
  },
  "Europe/Oslo": { offset: "+02:00", standard: "CEST" },
  "Europe/Paris": { offset: "+02:00", standard: "CEST" },
  "Europe/Podgorica": { offset: "+02:00", standard: "CEST" },
  "Europe/Prague": { offset: "+02:00", standard: "CEST" },
  "Europe/Riga": { offset: "+03:00", standard: "EEST" },
  "Europe/Rome": { offset: "+02:00", standard: "CEST" },
  "Europe/Samara": {
    offset: "+04:00",
    standard: "+04:00",
    daylight: "+04",
    daylightStandard: "+04",
  },
  "Europe/San_Marino": { offset: "+02:00", standard: "CEST" },
  "Europe/Sarajevo": { offset: "+02:00", standard: "CEST" },
  "Europe/Saratov": {
    offset: "+04:00",
    standard: "+04:00",
    daylight: "+04",
    daylightStandard: "+04",
  },
  "Europe/Simferopol": {
    offset: "+03:00",
    standard: "+03:00",
    daylight: "+03",
    daylightStandard: "+03",
  },
  "Europe/Skopje": { offset: "+02:00", standard: "CEST" },
  "Europe/Sofia": { offset: "+03:00", standard: "EEST" },
  "Europe/Stockholm": { offset: "+02:00", standard: "CEST" },
  "Europe/Tallinn": { offset: "+03:00", standard: "EEST" },
  "Europe/Tirane": { offset: "+02:00", standard: "CEST" },
  "Europe/Tiraspol": { offset: "+03:00", standard: "EEST" },
  "Europe/Ulyanovsk": {
    offset: "+04:00",
    standard: "+04:00",
    daylight: "+04",
    daylightStandard: "+04",
  },
  "Europe/Uzhgorod": { offset: "+03:00", standard: "EEST" },
  "Europe/Vaduz": { offset: "+02:00", standard: "CEST" },
  "Europe/Vatican": { offset: "+02:00", standard: "CEST" },
  "Europe/Vienna": { offset: "+02:00", standard: "CEST" },
  "Europe/Vilnius": { offset: "+03:00", standard: "EEST" },
  "Europe/Volgograd": {
    offset: "+03:00",
    standard: "+03:00",
    daylight: "+03",
    daylightStandard: "+03",
  },
  "Europe/Warsaw": { offset: "+02:00", standard: "CEST" },
  "Europe/Zagreb": { offset: "+02:00", standard: "CEST" },
  "Europe/Zaporozhye": { offset: "+03:00", standard: "EEST" },
  "Europe/Zurich": { offset: "+02:00", standard: "CEST" },
  GB: { offset: "+00:00", standard: "GMT" },
  "GB-Eire": { offset: "+00:00", standard: "GMT" },
  GMT: { offset: "+00:00", standard: "GMT" },
  "GMT+0": { offset: "+00:00", standard: "GMT" },
  "GMT-0": { offset: "+00:00", standard: "GMT" },
  GMT0: { offset: "+00:00", standard: "GMT" },
  Greenwich: { offset: "+00:00", standard: "GMT" },
  HST: {
    offset: "-10:00",
    standard: "-10:00",
    daylight: "-09",
    daylightStandard: "-10",
  },
  Hongkong: { offset: "+08:00", standard: "HKT" },
  Iceland: { offset: "+00:00", standard: "GMT" },
  "Indian/Antananarivo": {
    offset: "+03:00",
    standard: "+03:00",
    daylight: "+03",
    daylightStandard: "+03",
  },
  "Indian/Chagos": {
    offset: "+06:00",
    standard: "+06:00",
    daylight: "+06",
    daylightStandard: "+06",
  },
  "Indian/Christmas": {
    offset: "+07:00",
    standard: "+07:00",
    daylight: "+07",
    daylightStandard: "+07",
  },
  "Indian/Cocos": {
    offset: "+06:30",
    standard: "+06:30",
    daylight: "+06",
    daylightStandard: "+06",
  },
  "Indian/Comoro": {
    offset: "+03:00",
    standard: "+03:00",
    daylight: "+03",
    daylightStandard: "+03",
  },
  "Indian/Kerguelen": {
    offset: "+05:00",
    standard: "+05:00",
    daylight: "+05",
    daylightStandard: "+05",
  },
  "Indian/Mahe": {
    offset: "+04:00",
    standard: "+04:00",
    daylight: "+04",
    daylightStandard: "+04",
  },
  "Indian/Maldives": {
    offset: "+05:00",
    standard: "+05:00",
    daylight: "+05",
    daylightStandard: "+05",
  },
  "Indian/Mauritius": {
    offset: "+04:00",
    standard: "+04:00",
    daylight: "+04",
    daylightStandard: "+04",
  },
  "Indian/Mayotte": {
    offset: "+03:00",
    standard: "+03:00",
    daylight: "+03",
    daylightStandard: "+03",
  },
  "Indian/Reunion": {
    offset: "+04:00",
    standard: "+04:00",
    daylight: "+04",
    daylightStandard: "+04",
  },
  Iran: {
    offset: "+03:30",
    standard: "+03:30",
    daylight: "+04",
    daylightStandard: "+03",
  },
  Israel: { offset: "+03:00", standard: "IST" },
  Jamaica: {
    offset: "-05:00",
    standard: "-05:00",
    daylight: "-04",
    daylightStandard: "-05",
  },
  Japan: { offset: "+09:00", standard: "JST" },
  Kwajalein: {
    offset: "+12:00",
    standard: "+12:00",
    daylight: "+12",
    daylightStandard: "+12",
  },
  Libya: {
    offset: "+02:00",
    standard: "+02:00",
    daylight: "+02",
    daylightStandard: "+02",
  },
  MET: { offset: "+02:00", standard: "MEST" },
  MST: {
    offset: "-07:00",
    standard: "-07:00",
    daylight: "-06",
    daylightStandard: "-07",
  },
  MST7MDT: {
    offset: "-07:00",
    standard: "-07:00",
    daylight: "-06",
    daylightStandard: "-07",
  },
  "Mexico/BajaNorte": {
    offset: "-08:00",
    standard: "-08:00",
    daylight: "-07",
    daylightStandard: "-08",
  },
  "Mexico/BajaSur": {
    offset: "-07:00",
    standard: "-07:00",
    daylight: "-06",
    daylightStandard: "-07",
  },
  "Mexico/General": {
    offset: "-06:00",
    standard: "-06:00",
    daylight: "-05",
    daylightStandard: "-06",
  },
  NZ: {
    offset: "+12:00",
    standard: "+12:00",
    daylight: "+13",
    daylightStandard: "+12",
  },
  "NZ-CHAT": {
    offset: "+12:45",
    standard: "+12:45",
    daylight: "+13",
    daylightStandard: "+12",
  },
  Navajo: {
    offset: "-07:00",
    standard: "-07:00",
    daylight: "-06",
    daylightStandard: "-07",
  },
  PRC: {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  PST8PDT: {
    offset: "-08:00",
    standard: "-08:00",
    daylight: "-07",
    daylightStandard: "-08",
  },
  "Pacific/Apia": {
    offset: "+13:00",
    standard: "+13:00",
    daylight: "+14",
    daylightStandard: "+13",
  },
  "Pacific/Auckland": {
    offset: "+12:00",
    standard: "+12:00",
    daylight: "+13",
    daylightStandard: "+12",
  },
  "Pacific/Bougainville": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Pacific/Chatham": {
    offset: "+12:45",
    standard: "+12:45",
    daylight: "+13",
    daylightStandard: "+12",
  },
  "Pacific/Chuuk": {
    offset: "+10:00",
    standard: "+10:00",
    daylight: "+10",
    daylightStandard: "+10",
  },
  "Pacific/Easter": {
    offset: "-06:00",
    standard: "-06:00",
    daylight: "-05",
    daylightStandard: "-06",
  },
  "Pacific/Efate": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Pacific/Enderbury": {
    offset: "+13:00",
    standard: "+13:00",
    daylight: "+13",
    daylightStandard: "+13",
  },
  "Pacific/Fakaofo": {
    offset: "+13:00",
    standard: "+13:00",
    daylight: "+13",
    daylightStandard: "+13",
  },
  "Pacific/Fiji": {
    offset: "+12:00",
    standard: "+12:00",
    daylight: "+13",
    daylightStandard: "+12",
  },
  "Pacific/Funafuti": {
    offset: "+12:00",
    standard: "+12:00",
    daylight: "+12",
    daylightStandard: "+12",
  },
  "Pacific/Galapagos": {
    offset: "-06:00",
    standard: "-06:00",
    daylight: "-06",
    daylightStandard: "-06",
  },
  "Pacific/Gambier": {
    offset: "-09:00",
    standard: "-09:00",
    daylight: "-09",
    daylightStandard: "-09",
  },
  "Pacific/Guadalcanal": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Pacific/Guam": {
    offset: "+10:00",
    standard: "+10:00",
    daylight: "+10",
    daylightStandard: "+10",
  },
  "Pacific/Honolulu": {
    offset: "-10:00",
    standard: "-10:00",
    daylight: "-10",
    daylightStandard: "-10",
  },
  "Pacific/Johnston": {
    offset: "-10:00",
    standard: "-10:00",
    daylight: "-10",
    daylightStandard: "-10",
  },
  "Pacific/Kiritimati": {
    offset: "+14:00",
    standard: "+14:00",
    daylight: "+14",
    daylightStandard: "+14",
  },
  "Pacific/Kosrae": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Pacific/Kwajalein": {
    offset: "+12:00",
    standard: "+12:00",
    daylight: "+12",
    daylightStandard: "+12",
  },
  "Pacific/Majuro": {
    offset: "+12:00",
    standard: "+12:00",
    daylight: "+12",
    daylightStandard: "+12",
  },
  "Pacific/Marquesas": {
    offset: "-09:30",
    standard: "-09:30",
    daylight: "-09",
    daylightStandard: "-09",
  },
  "Pacific/Midway": {
    offset: "-11:00",
    standard: "-11:00",
    daylight: "-11",
    daylightStandard: "-11",
  },
  "Pacific/Nauru": {
    offset: "+12:00",
    standard: "+12:00",
    daylight: "+12",
    daylightStandard: "+12",
  },
  "Pacific/Niue": {
    offset: "-11:00",
    standard: "-11:00",
    daylight: "-11",
    daylightStandard: "-11",
  },
  "Pacific/Norfolk": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Pacific/Noumea": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Pacific/Pago_Pago": {
    offset: "-11:00",
    standard: "-11:00",
    daylight: "-11",
    daylightStandard: "-11",
  },
  "Pacific/Palau": {
    offset: "+09:00",
    standard: "+09:00",
    daylight: "+09",
    daylightStandard: "+09",
  },
  "Pacific/Pitcairn": {
    offset: "-08:00",
    standard: "-08:00",
    daylight: "-08",
    daylightStandard: "-08",
  },
  "Pacific/Pohnpei": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Pacific/Ponape": {
    offset: "+11:00",
    standard: "+11:00",
    daylight: "+11",
    daylightStandard: "+11",
  },
  "Pacific/Port_Moresby": {
    offset: "+10:00",
    standard: "+10:00",
    daylight: "+10",
    daylightStandard: "+10",
  },
  "Pacific/Rarotonga": {
    offset: "-10:00",
    standard: "-10:00",
    daylight: "-10",
    daylightStandard: "-10",
  },
  "Pacific/Saipan": {
    offset: "+10:00",
    standard: "+10:00",
    daylight: "+10",
    daylightStandard: "+10",
  },
  "Pacific/Samoa": {
    offset: "-11:00",
    standard: "-11:00",
    daylight: "-11",
    daylightStandard: "-11",
  },
  "Pacific/Tahiti": {
    offset: "-10:00",
    standard: "-10:00",
    daylight: "-10",
    daylightStandard: "-10",
  },
  "Pacific/Tarawa": {
    offset: "+12:00",
    standard: "+12:00",
    daylight: "+12",
    daylightStandard: "+12",
  },
  "Pacific/Tongatapu": {
    offset: "+13:00",
    standard: "+13:00",
    daylight: "+14",
    daylightStandard: "+13",
  },
  "Pacific/Truk": {
    offset: "+10:00",
    standard: "+10:00",
    daylight: "+10",
    daylightStandard: "+10",
  },
  "Pacific/Wake": {
    offset: "+12:00",
    standard: "+12:00",
    daylight: "+12",
    daylightStandard: "+12",
  },
  "Pacific/Wallis": {
    offset: "+12:00",
    standard: "+12:00",
    daylight: "+12",
    daylightStandard: "+12",
  },
  "Pacific/Yap": {
    offset: "+10:00",
    standard: "+10:00",
    daylight: "+10",
    daylightStandard: "+10",
  },
  Poland: { offset: "+02:00", standard: "CEST" },
  Portugal: { offset: "+01:00", standard: "WEST" },
  ROC: {
    offset: "+08:00",
    standard: "+08:00",
    daylight: "+08",
    daylightStandard: "+08",
  },
  ROK: { offset: "+09:00", standard: "KST" },
  Singapore: { offset: "+08:00", standard: "SGT" },
  Turkey: { offset: "+03:00", standard: "TRT" },
  UCT: { offset: "+00:00", standard: "GMT" },
  "US/Alaska": {
    offset: "-08:00",
    standard: "-09:00",
    daylight: "-08",
    daylightStandard: "-09",
  },
  "US/Aleutian": {
    offset: "-10:00",
    standard: "-10:00",
    daylight: "-09",
    daylightStandard: "-10",
  },
  "US/Arizona": {
    offset: "-07:00",
    standard: "-07:00",
    daylight: "-07",
    daylightStandard: "-07",
  },
  "US/Central": {
    offset: "-05:00",
    standard: "-06:00",
    daylight: "-05",
    daylightStandard: "-06",
  },
  "US/Eastern": {
    offset: "-04:00",
    standard: "-05:00",
    daylight: "-04",
    daylightStandard: "-05",
  },
  "US/East-Indiana": {
    offset: "-04:00",
    standard: "-05:00",
    daylight: "-04",
    daylightStandard: "-05",
  },
  "US/Hawaii": {
    offset: "-10:00",
    standard: "-10:00",
    daylight: "-10",
    daylightStandard: "-10",
  },
  "US/Indiana-Starke": {
    offset: "-05:00",
    standard: "-06:00",
    daylight: "-05",
    daylightStandard: "-06",
  },
  "US/Michigan": {
    offset: "-04:00",
    standard: "-04:00",
    daylight: "-04",
    daylightStandard: "-04",
  },
  "US/Mountain": {
    offset: "-06:00",
    standard: "-07:00",
    daylight: "-06",
    daylightStandard: "-07",
  },
  "US/Pacific": {
    offset: "-07:00",
    standard: "-08:00",
    daylight: "-07",
    daylightStandard: "-08",
  },
  "US/Samoa": {
    offset: "-11:00",
    standard: "-11:00",
    daylight: "-11",
    daylightStandard: "-11",
  },
  UTC: { offset: "+00:00", standard: "GMT" },
  Universal: { offset: "+00:00", standard: "GMT" },
  "W-SU": { offset: "+03:00", standard: "MSK" },
  WET: { offset: "+00:00", standard: "WEST" },
  Zulu: { offset: "+00:00", standard: "GMT" },
};
